import gridProgress from '@/assets/images/backgroundImage.png';
// import { FontFamily } from '/@/components/TextStyle/constant';
export default {
  label: '栅格进度条',
  option: {
    title: '栅格进度条',
    name: '栅格进度条',
    icon: 'icon-progress',
    img: gridProgress,
    top: 0,
    left: 0,
    dataType: 0,
    data: [
      {
        value: 7,
        max: 10,
      },
    ],
    dataFormatter: '',
    stylesFormatter: '',
    component: {
      width: 300,
      height: 100,
      name: 'gridProgress',
      prop: 'gridProgress',
    },
    option: {
      animation: {
        show: false,
        type: 'linear',
        duration: 300,
        dynamicEffect: true,
        value: 0,
        elastic: 100,
        damp: 10,
        quality: 1,
      },
      grid: {
        height: 20,
        width: 20,
        radius: 5,
        space: 0.2,
        startColor: '#1890FF',
        endColor: '#1EE7E7',
        backgroundColor: 'rgba(230, 247,255, 0.1)',
        underline: false,
      },
      text: {
        // fontFamily: FontFamily.default,
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 26,
        color: '#e6f7ff',
        realValue: true,
        digits: 1,
        offsetY: 4,
        offsetX: 0,
        showUnit: false,
        unit: '天',
      },
      unit: {
        // fontFamily: FontFamily.default,
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 26,
        color: '#e6f7ff',
        offsetY: 4,
      },
      position: {
        position: 'adaptive',
        offsetX: 0,
        offsetY: 0,
      },
    },
  },
};
