// import flop from '/@/assets/images/flop.png';
let baseUrl = '.';

export default {
  label: '翻牌器v2',
  option: {
    title: '翻牌器v2',
    name: '翻牌器v2',
    icon: 'icon-flop',
    // img: flop,
    top: 0,
    left: 0,
    dataType: 0,
    dataMethod: 'get',
    time: 5000,
    url: baseUrl + '/flop',
    child: {
      index: [],
      paramName: '',
    },
    data: 1235 ,
    dataFormatter: '',
    stylesFormatter: '',
    component: {
      width: 500,
      height: 200,
      name: 'FlopNew',
      prop: 'FlopNew',
    },
    option: {
      prefix: {
        show: true,
        text: '',
        fontSize: 16,
        lineHeight: 24,
        // fontFamily: FontFamily.default,
        color: '#fff',
        fontWeight: 'normal',
        offsetX: 50,
        offsetY: 20,
      },
      number: {
        fontSize: 30,
        color: '#fff',
        // fontFamily: FontFamily.default,
        fontWeight: 'bold',
        lineHeight: 38,
        widthAuto: false,
        space: 10,
        backgroundImage: '',
        offsetX: 0,
        offsetY: 0,
        marginLeft: 10,
        marginRight: 10,
        useGroup: false,
        separator: ',',
        decimal: 2,
        duration: 1,
        intervals: 10,
        animation: true,
      },
      suffix: {
        show: true,
        text: '',
        fontSize: 16,
        // fontFamily: FontFamily.default,
        fontWeight: 'normal',
        color: '#fff',
        lineHeight: 24,
        offsetX: 0,
        offsetY: 0,
      },
    },
  },
};
